# -*- coding: utf-8 -*-
"""Passive Proxy-History statistics, Aura-aware aggregation and annotations.

No HTTP is sent.  Classification follows the SF Helper precedence while
splitting HTML screens into conventional Web and SPA shells.  Aggregation is
intentionally limited to Aura SPA updates and only adjacent same-key runs.
"""

import hashlib
import json
import re

from csvlistinput.utils import to_display_text

try:
    from urllib import unquote_plus
except ImportError:
    from urllib.parse import unquote_plus

WEB_SCREEN = u"Web画面"
WEB_PART = u"Web個別パーツ取得"
SPA_SCREEN = u"SPA（画面）"
SPA_UPDATE = u"SPA（画面更新）"
API = u"API"

CLASS_ORDER = [WEB_SCREEN, WEB_PART, SPA_SCREEN, SPA_UPDATE, API]
CLASS_DEFINITIONS = {
    WEB_SCREEN: u"SPAシェルではないHTMLレスポンス。",
    WEB_PART: u"JavaScript、CSS、画像、フォント、メディア等の静的アセット。",
    SPA_SCREEN: u"Aura、Lightning、LWC、React、Vue、Angularの起動マーカーを含むHTML。",
    SPA_UPDATE: u"Auraのパス・message・aura.contextを含む画面更新通信。",
    API: u"上記以外（auraAnalyticを含む）の通信。",
}

_STATIC_EXTS = set(['js', 'css', 'map', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'ico', 'webp',
                    'woff', 'woff2', 'ttf', 'eot', 'mp4', 'webm', 'mp3', 'pdf'])
_STATIC_MIME = ('javascript', 'css', 'image/', 'font/', 'audio/', 'video/', 'application/pdf')
_AURA_MARKERS = ('/aura', 'sfsites/aura', 'auracmpdef', 'auraresources')
_SPA_HTML_MARKERS = ('aura://', 'lightning', 'lwc', 'react', 'vue', 'angular')
_LEADING_NUMBER_RE = re.compile(r'^\s*\[(\d+)\]\s*')
_OBJECT_KEYS = set(['objectapiname', 'objecttype', 'sobjecttype', 'entityname', 'objectname'])
# Accept the canonical form produced by MyTools as well as tags created by
# older builds/manual editing: whitespace, single quotes, and an unquoted
# token are harmless variations.  Matching is case-insensitive because
# History comments are user-controlled text.
_GROUP_TAG_RE = re.compile(
    r'\[\s*group\s*=\s*(?:"([^"\]\r\n]+)"|\'([^\'\]\r\n]+)\'|([^\]\s]+))\s*\]',
    re.IGNORECASE)
# Statistics annotations from both current and earlier UI builds.  Keep this
# deliberately enumerated: a broad "remove all [..]" rule would also destroy
# user numbering and [group="..."] metadata.
_STATISTICS_TAG_RE = re.compile(
    r'\[\s*(?:'
    r'Web画面|Web個別パーツ取得|'
    r'SPA[（(]画面[）)]|SPA[（(]画面更新[）)]|API|'
    r'Web\s*Screen|Web\s*Part|SPA\s*Screen|SPA\s*Update|'
    r'Aggregation\s*Target|'
    r'集約対象(?:\s*_?\s*集約先\s*(?:No)?[^\]\r\n]+)?|'
    r'mytools\s*:\s*statistics\s*:\s*(?:class|aggregation)\s*=\s*[^\]\r\n]+'
    r')\s*\]\s*', re.IGNORECASE)
_STATISTICS_EXACT_TAGS = (
    u'[Web画面]', u'[Web個別パーツ取得]', u'[SPA（画面）]', u'[SPA（画面更新）]', u'[API]',
    # Historical/manual tags often use ASCII parentheses instead of the
    # full-width form emitted by the current UI.
    u'[SPA(画面)]', u'[SPA(画面更新)]',
    u'[集約対象]',
)
_STATISTICS_LABELS = set(tag[1:-1] for tag in _STATISTICS_EXACT_TAGS if tag != u'[集約対象]')


def _is_statistics_label(label):
    """True only for a bracket label owned by Statistics.

    This deliberately recognizes every ``集約対象...`` suffix generated by
    Statistics, including an arbitrary representative Number.  Groups and
    numbering have different labels and are never considered Statistics.
    """
    compact = u''.join((label or u'').strip().split())
    if compact in _STATISTICS_LABELS:
        return True
    lowered = compact.lower()
    return (compact.startswith(u'集約対象') or lowered in (
        u'webscreen', u'webpart', u'spascreen', u'spaupdate', u'aggregationtarget') or
        lowered.startswith(u'mytools:statistics:') or
        lowered.startswith(u'trafficclass=') or lowered.startswith(u'category=') or
        lowered.startswith(u'protocol='))


def _strip_statistics_tags(comment):
    """Remove Statistics-owned [tags] without relying on Java regex Unicode.

    Burp's Jython bridge can expose comments as Java-backed strings.  A small
    literal bracket scanner is more predictable than a non-ASCII regex there
    and accepts all representative-number variations.
    """
    out = []
    cursor = 0
    length = len(comment)
    while cursor < length:
        start = comment.find(u'[', cursor)
        if start == -1:
            out.append(comment[cursor:])
            break
        end = comment.find(u']', start + 1)
        if end == -1:
            out.append(comment[cursor:])
            break
        label = comment[start + 1:end]
        if _is_statistics_label(label):
            out.append(comment[cursor:start])
        else:
            out.append(comment[cursor:end + 1])
        cursor = end + 1
    return u''.join(out)


def _comment_text(comment):
    """Normalize Burp/Jython Java strings and byte comments to Unicode."""
    if comment is None:
        return u''
    try:
        unicode
        is_jython = True
    except NameError:
        is_jython = False
    if is_jython:
        # Jython 2's ``str``/``bytes`` is raw byte-string space.  Decode it
        # explicitly before unicode() can attempt its implicit ASCII path.
        if isinstance(comment, str):
            try:
                return comment.decode('utf-8')
            except Exception:
                return comment.decode('latin-1')
    else:
        if isinstance(comment, bytes):
            try:
                return comment.decode('utf-8')
            except Exception:
                return comment.decode('latin-1')
    try:
        return unicode(comment)
    except NameError:
        return str(comment)
    except Exception:
        # Some Java-backed String proxies do not satisfy str/unicode in
        # Jython.  Their textual representation is still recoverable, but
        # must follow the same explicit byte decoding discipline.
        try:
            raw = str(comment)
            try:
                return raw.decode('utf-8')
            except Exception:
                return raw.decode('latin-1')
        except Exception:
            return u''


def _text(helpers, value):
    if value is None:
        return u''
    try:
        return helpers.bytesToString(value)
    except Exception:
        if isinstance(value, bytes):
            return value.decode('latin-1')
        return value


def _headers(text):
    return text.split('\r\n\r\n', 1)[0].split('\n')


def _header(headers, name):
    prefix = name.lower() + ':'
    for line in headers[1:]:
        if line.lower().startswith(prefix):
            return line.split(':', 1)[1].strip()
    return ''


def _request_parts(text):
    lines = _headers(text)
    first = lines[0].split() if lines else []
    method = first[0] if first else ''
    target = first[1] if len(first) > 1 else '/'
    path, _, query = target.partition('?')
    body = text.split('\r\n\r\n', 1)[1] if '\r\n\r\n' in text else ''
    return method, path, query, body, lines


def _short_descriptor(value):
    value = (value or '').split('://', 1)[-1]
    if '/ACTION$' in value:
        left, action = value.split('/ACTION$', 1)
        return '%s/%s' % (left.split('.')[-1].split('/')[-1], action)
    return value.split('.')[-1]


def _aura_key(path, body, headers):
    """Build the conservative SF-Helper-inspired aggregation key."""
    message = ''
    page_uri = ''
    for pair in body.split('&'):
        key, sep, value = pair.partition('=')
        if not sep:
            continue
        if key == 'message':
            message = unquote_plus(value)
        elif key == 'aura.pageURI':
            page_uri = unquote_plus(value)
    descriptors = []
    objects = []
    apex_calls = []
    def collect_objects(value, key=''):
        if isinstance(value, dict):
            for child_key, child_value in value.items():
                collect_objects(child_value, to_display_text(child_key))
        elif isinstance(value, list):
            for child_value in value:
                collect_objects(child_value, key)
        elif to_display_text(key).lower() in _OBJECT_KEYS and value:
            objects.append(to_display_text(value))
    try:
        actions = json.loads(message).get('actions', [])
        for action in actions:
            if isinstance(action, dict):
                descriptor = _short_descriptor(action.get('descriptor', ''))
                if descriptor:
                    descriptors.append(descriptor)
                params = action.get('params', {})
                collect_objects(params)
                if 'ApexActionController' in (action.get('descriptor', '') or '') and isinstance(params, dict):
                    apex_name = params.get('classname') or params.get('apexClass') or ''
                    apex_method = params.get('method') or params.get('methodName') or ''
                    if apex_name or apex_method:
                        apex_calls.append('%s.%s' % (apex_name, apex_method))
    except Exception:
        pass
    auth = 'auth' if _header(headers, 'Cookie') or _header(headers, 'Authorization') else 'guest'
    if descriptors:
        return 'AURA|%s|%s|obj=%s|apex=%s|%s|%s' % (
            path, ','.join(sorted(set(descriptors))), ','.join(sorted(set(objects))) or '-',
            ','.join(sorted(set(apex_calls))) or '-', page_uri, auth)
    # Component-resource requests without descriptors are safe to merge only
    # when their full relevant request content is identical.
    digest = hashlib.sha1((path + '\n' + body + '\n' + auth).encode('utf-8')).hexdigest()
    return 'AURA-CONTENT|%s' % digest


def classify_packet(path, request_body, response_text, response_mime=''):
    """Return one of the five documented class labels, in precedence order."""
    lowered_path = (path or '').lower()
    lowered_body = (request_body or '').lower()
    response_lower = (response_text or '').lower()
    mime = (response_mime or '').lower()
    if 'auraanalytic' in lowered_path:
        return API
    if any(marker in lowered_path for marker in _AURA_MARKERS) or 'message=' in lowered_body or 'aura.context=' in lowered_body:
        return SPA_UPDATE
    ext = lowered_path.rsplit('.', 1)[-1] if '.' in lowered_path.rsplit('/', 1)[-1] else ''
    if ext in _STATIC_EXTS or any(marker in mime for marker in _STATIC_MIME):
        return WEB_PART
    if 'html' in mime or '<html' in response_lower:
        return SPA_SCREEN if any(marker in response_lower for marker in _SPA_HTML_MARKERS) else WEB_SCREEN
    return API


def analyze_history(callbacks, helpers, start_packet_no=None, end_packet_no=None, cancel_check=None):
    """Analyze inclusive one-based History bounds and return packet records."""
    records = []
    packet_no = 0
    for item in callbacks.getProxyHistory():
        packet_no += 1
        if cancel_check and cancel_check():
            break
        if start_packet_no is not None and packet_no < start_packet_no:
            continue
        if end_packet_no is not None and packet_no > end_packet_no:
            break
        request = _text(helpers, item.getRequest())
        response = _text(helpers, item.getResponse())
        method, path, query, body, request_headers = _request_parts(request)
        response_headers = _headers(response)
        response_mime = _header(response_headers, 'Content-Type')
        cls = classify_packet(path, body, response, response_mime)
        records.append({'packet_no': packet_no, 'item': item, 'class': cls, 'method': method,
                        'path': path, 'query': query, 'body': body, 'headers': request_headers,
                        'agg_key': _aura_key(path, body, request_headers) if cls == SPA_UPDATE else None,
                        'agg_role': u'single', 'agg_rep': None})
    _assign_aggregation(records)
    return records


def _assign_aggregation(records):
    """Mark first/subsequent packets of adjacent same-key Aura runs."""
    current = []
    current_key = None
    def finish(run):
        if len(run) <= 1:
            return
        representative = run[0]
        representative['agg_role'] = u'representative'
        representative['agg_rep'] = representative
        for record in run[1:]:
            record['agg_role'] = u'target'
            record['agg_rep'] = representative
    for record in records:
        if record['class'] != SPA_UPDATE:
            continue
        if current and record['agg_key'] == current_key:
            current.append(record)
        else:
            finish(current)
            current = [record]
            current_key = record['agg_key']
    finish(current)


def summary_rows(records):
    rows = []
    for label in CLASS_ORDER:
        total = len([record for record in records if record['class'] == label])
        reduced = len([record for record in records
                       if record['class'] == label and record['agg_role'] != u'target'])
        rows.append({'class': label, 'including_aggregated': total,
                     'excluding_aggregated': reduced, 'definition': CLASS_DEFINITIONS[label]})
    return rows


def _v2_origin_category(path, body):
    """Statistics2用の5分類。通信から確定できないものは安全側でUnknown。"""
    lowered_path = (path or u'').lower()
    if lowered_path.startswith(u'/services/apexrest/'):
        return u'ApexREST'
    if (lowered_path.startswith(u'/services/data/') or lowered_path.startswith(u'/services/connect/') or
            lowered_path.startswith(u'/services/async/') or lowered_path.startswith(u'/services/soap/')):
        return u'SalesforceREST'
    if u'message=' not in (body or u'').lower():
        return u'Unknown'
    message = u''
    for pair in (body or u'').split(u'&'):
        key, separator, value = pair.partition(u'=')
        if separator and key == u'message':
            message = unquote_plus(value)
            break
    try:
        actions = json.loads(message).get('actions', [])
    except Exception:
        actions = []
    categories = set()
    for action in actions:
        if not isinstance(action, dict):
            continue
        descriptor = to_display_text(action.get('descriptor', u''))
        scheme, separator, controller = descriptor.partition(u'://')
        if not separator:
            continue
        lowered_scheme = scheme.lower()
        lowered_controller = controller.lower()
        if lowered_scheme == u'apex':
            categories.add(u'Apexカスタム')
        elif lowered_scheme in (u'aura', u'servicecomponent'):
            if lowered_controller.endswith(u'apexactioncontroller/action$execute'):
                params = action.get('params') or {}
                class_name = to_display_text(params.get('classname') or params.get('apexClass') or
                                              params.get('className') or u'')
                if class_name:
                    categories.add(u'Apexカスタム')
                else:
                    categories.add(u'Unknown')
            else:
                categories.add(u'Salesforce標準')
    if len(categories) == 1:
        return next(iter(categories))
    return u'Unknown'


def _v2_protocol(path, body, response, response_mime, traffic_class):
    lowered_path = (path or u'').lower()
    lowered_body = (body or u'').lower()
    lowered_response = (response or u'').lower()
    mime = (response_mime or u'').lower()
    if traffic_class == SPA_UPDATE:
        return u'Aura'
    if u'graphql' in lowered_path or u'"query"' in lowered_body or u'query{' in lowered_body:
        return u'GraphQL'
    if u'/ui-api/' in lowered_path or u'/uiapi/' in lowered_path:
        return u'UI API'
    if (lowered_path.startswith(u'/services/') or lowered_path.startswith(u'/api/') or
            u'/rest/' in lowered_path or u'json' in mime or u'json' in lowered_body):
        return u'REST'
    if any(lowered_path.endswith(u'.' + extension) for extension in _STATIC_EXTS):
        return u'File'
    if u'html' in mime or u'<html' in lowered_response:
        return u'Web'
    return u'Other'


def analyze_history_v2(callbacks, helpers, start_packet_no=None, end_packet_no=None, cancel_check=None):
    """Statisticsの集約規則を保ったままTraffic Class/Category/Protocolを付与する。"""
    records = analyze_history(callbacks, helpers, start_packet_no, end_packet_no, cancel_check)
    for record in records:
        response = _text(helpers, record['item'].getResponse())
        response_mime = _header(_headers(response), 'Content-Type')
        record['traffic_class'] = record['class']
        record['category'] = _v2_origin_category(record['path'], record['body'])
        record['protocol'] = _v2_protocol(record['path'], record['body'], response,
                                          response_mime, record['traffic_class'])
    return records


def summary_rows_v2(records):
    """Traffic Class × Category × Protocol単位で、集約前後の件数を返す。"""
    grouped = {}
    for record in records:
        traffic_class = record.get('traffic_class') or record.get('class') or API
        key = (traffic_class, record.get('category') or u'Unknown', record.get('protocol') or u'Other')
        current = grouped.setdefault(key, {'traffic_class': traffic_class, 'category': key[1],
                                           'protocol': key[2], 'including_aggregated': 0,
                                           'excluding_aggregated': 0,
                                           'definition': _v2_definition(traffic_class, key[1], key[2])})
        current['including_aggregated'] += 1
        if record.get('agg_role') != u'target':
            current['excluding_aggregated'] += 1
    return sorted(grouped.values(), key=lambda row: (
        CLASS_ORDER.index(row['traffic_class']) if row['traffic_class'] in CLASS_ORDER else len(CLASS_ORDER),
        row['category'], row['protocol']))


_CATEGORY_DEFINITIONS_V2 = {
    u'Salesforce標準': u'Salesforce標準機能・標準Aura actionと推定。',
    u'Apexカスタム': u'組織または管理パッケージのApex actionと推定。',
    u'ApexREST': u'/services/apexrest/ のApex REST endpoint。',
    u'SalesforceREST': u'/services/data/等のSalesforce REST API。',
    u'Unknown': u'通信だけではSalesforce/Apex由来を確定できない。',
}
_PROTOCOL_DEFINITIONS_V2 = {
    u'Aura': u'Aura message/contextを使う通信。',
    u'GraphQL': u'GraphQL queryまたはmutationを含む通信。',
    u'UI API': u'Salesforce UI API endpoint。',
    u'REST': u'JSON中心のREST形式通信。',
    u'Web': u'HTML画面の取得。',
    u'File': u'静的ファイル・メディアの取得。',
    u'Other': u'上記のプロトコルを判定できない通信。',
}

_TRAFFIC_CLASS_SHORT_V2 = {
    WEB_SCREEN: u'Web画面',
    WEB_PART: u'画面部品',
    SPA_SCREEN: u'SPA画面',
    SPA_UPDATE: u'SPA更新',
    API: u'API通信',
}
_CATEGORY_SHORT_V2 = {
    u'Salesforce標準': u'Salesforce標準（推定）',
    u'Apexカスタム': u'Apexカスタム（推定）',
    u'ApexREST': u'Apex REST',
    u'SalesforceREST': u'Salesforce REST',
    u'Unknown': u'由来不明',
}
_PROTOCOL_SHORT_V2 = {
    u'Aura': u'Aura通信',
    u'GraphQL': u'GraphQL通信',
    u'UI API': u'UI API通信',
    u'REST': u'REST通信',
    u'Web': u'Web通信',
    u'File': u'静的ファイル',
    u'Other': u'その他の通信',
}


def _v2_definition(traffic_class, category, protocol):
    """Statistics2の集計行を短い自然な説明にする。"""
    return u' / '.join((
        _PROTOCOL_SHORT_V2.get(protocol, u'通信形式不明'),
        _TRAFFIC_CLASS_SHORT_V2.get(traffic_class, u'分類不明'),
        _CATEGORY_SHORT_V2.get(category, u'由来不明')))


def _leading_number(comment):
    match = _LEADING_NUMBER_RE.match(comment or '')
    return match.group(1) if match else None


def _append_tag(comment, tag):
    marker = u'[%s]' % tag
    if marker in (comment or ''):
        return comment or u''
    return ((comment or u'').rstrip() + (u' ' if comment else u'') + marker)


def _prepend_tags(comment, tags):
    """Statistics2のタグを既存Commentの先頭へ、順序を保って挿入する。"""
    prefix = u' '.join(u'[%s]' % tag for tag in tags if tag)
    text = (comment or u'').strip()
    return prefix + (u' ' + text if prefix and text else text)


def group_names(comment):
    """Return sorted, de-duplicated group names from explicit group tags."""
    names = []
    for match in _GROUP_TAG_RE.findall(_comment_text(comment)):
        name = next((value for value in match if value), u'').strip()
        if name:
            names.append(name)
    return sorted(set(names))


def group_display(comment):
    return u', '.join(group_names(comment))


def annotate_analysis(records, add_class_tags=False, add_aggregation_tags=False,
                     clear_comments_first=False, color_targets=False, color_name='gray'):
    """Apply explicitly requested History annotations; return update counts."""
    updated = colored = 0
    original_numbers = dict((record['packet_no'], _leading_number(record['item'].getComment() or u''))
                            for record in records)
    for record in records:
        old = record['item'].getComment() or u''
        comment = u'' if clear_comments_first else old
        if add_class_tags:
            comment = _append_tag(comment, record['class'])
        if add_aggregation_tags and record['agg_role'] == u'target':
            representative = record['agg_rep']
            rep_number = original_numbers.get(representative['packet_no']) if representative else None
            # A representative can be outside the selected export set and
            # therefore have no leading [number].  Never lose the destination
            # in that case: History Packet No is stable for the current view
            # and makes the aggregation relationship immediately traceable.
            tag = (u'集約対象_集約先No%s' % rep_number if rep_number else
                   (u'集約対象_集約先PacketNo%s' % representative['packet_no']
                    if representative else u'集約対象'))
            comment = _append_tag(comment, tag)
        if comment != old:
            record['item'].setComment(comment)
            updated += 1
        if color_targets and record['agg_role'] == u'target':
            record['item'].setHighlight(color_name)
            colored += 1
    return updated, colored


def annotate_analysis_v2(records, add_dimension_tags=True, add_aggregation_tags=False,
                        clear_comments_first=False, color_targets=False, color_name='gray'):
    """Statistics2用注釈。3軸タグと集約タグを既存Commentの先頭へ追加する。"""
    updated = colored = 0
    original_numbers = dict((record['packet_no'], _leading_number(_comment_text(record['item'].getComment() or u'')))
                            for record in records)
    for record in records:
        old = _comment_text(record['item'].getComment() or u'')
        comment = u'' if clear_comments_first else _strip_statistics2_dimension_tags(old)
        tags = []
        if add_dimension_tags:
            tags.extend((u'Protocol=%s' % (record.get('protocol') or u'Other'),
                         u'Traffic Class=%s' % (record.get('traffic_class') or record.get('class') or API),
                         u'Category=%s' % (record.get('category') or u'Unknown')))
        if add_aggregation_tags and record['agg_role'] == u'target':
            representative = record['agg_rep']
            rep_number = original_numbers.get(representative['packet_no']) if representative else None
            tags.append(u'集約対象_集約先No%s' % rep_number if rep_number else
                        (u'集約対象_集約先PacketNo%s' % representative['packet_no']
                         if representative else u'集約対象'))
        comment = _prepend_tags(comment, tags) if tags else comment
        if comment != old:
            record['item'].setComment(comment)
            updated += 1
        if color_targets and record['agg_role'] == u'target':
            record['item'].setHighlight(color_name)
            colored += 1
    return updated, colored


def _strip_statistics2_dimension_tags(comment):
    """Statistics2自身が生成した3軸タグだけを差し替え前に除去する。"""
    labels = (u'trafficclass=', u'category=', u'protocol=')
    out = []
    cursor = 0
    while cursor < len(comment):
        start = comment.find(u'[', cursor)
        if start == -1:
            out.append(comment[cursor:])
            break
        end = comment.find(u']', start + 1)
        if end == -1:
            out.append(comment[cursor:])
            break
        label = comment[start + 1:end]
        compact = u''.join(label.strip().split()).lower()
        if any(compact.startswith(prefix) for prefix in labels):
            out.append(comment[cursor:start])
        else:
            out.append(comment[cursor:end + 1])
        cursor = end + 1
    return u''.join(out).strip()


def clear_analysis_annotations(callbacks, start_packet_no=None, end_packet_no=None):
    """Remove only tags generated by Statistics from History comments.

    User numbering (`[0001]`), groups (`[group="..."]`) and unrelated
    bracket annotations remain untouched.
    """
    changed = packet_no = 0
    for item in callbacks.getProxyHistory():
        packet_no += 1
        if start_packet_no is not None and packet_no < start_packet_no:
            continue
        if end_packet_no is not None and packet_no > end_packet_no:
            break
        # ``getComment()`` can be a Java String, unicode, or Jython's raw
        # byte-string.  Comparing a Unicode ``new`` value to the latter asks
        # Jython to ASCII-decode Japanese tag bytes and can silently leave a
        # comment behind (or fail the background operation). Normalize before
        # both substitution *and* comparison.
        old = _comment_text(item.getComment() or u'')
        new = _strip_statistics_tags(old)
        # Retain the regular-expression pass only for unusual historic
        # whitespace spellings that pre-date the current tag format.
        new = _STATISTICS_TAG_RE.sub(u'', new)
        # Removing adjacent tags can leave several spaces before an existing
        # user comment.  Collapse only horizontal whitespace; line breaks in
        # a deliberately multi-line Comment are preserved.
        new = re.sub(r'[ \t]{2,}', u' ', new).strip()
        if new != old:
            item.setComment(new)
            changed += 1
    return changed


def number_all(callbacks, start_number, digits):
    """Prefix every current History comment with a zero-padded sequence."""
    changed = 0
    number = start_number
    for item in callbacks.getProxyHistory():
        old = item.getComment() or u''
        rest = _LEADING_NUMBER_RE.sub(u'', old, count=1)
        item.setComment((u'[%0*d] ' % (digits, number)) + rest)
        number += 1
        changed += 1
    return changed


def number_selected(messages, start_number=1, digits=4):
    """Apply the standard leading-number format to selected History items.

    This is the selected-packet counterpart of ``number_all``.  Existing
    leading numbers are replaced rather than stacked; every other comment
    tag/value is preserved for the subsequent Statistics annotation step.
    """
    changed = 0
    number = start_number
    for item in messages:
        old = _comment_text(item.getComment() or u'')
        rest = _LEADING_NUMBER_RE.sub(u'', old).lstrip()
        new = (u'[%0*d]' % (digits, number)) + (u' ' + rest if rest else u'')
        if new != old:
            item.setComment(new)
            changed += 1
        number += 1
    return changed


def remove_numbering(callbacks):
    changed = 0
    for item in callbacks.getProxyHistory():
        old = item.getComment() or u''
        new = _LEADING_NUMBER_RE.sub(u'', old, count=1)
        if new != old:
            item.setComment(new)
            changed += 1
    return changed


def add_group(items, group_name):
    tag = (group_name or u'').strip()
    if not tag or '"' in tag or '[' in tag or ']' in tag:
        raise ValueError('Group name is empty.')
    changed = 0
    for item in items:
        old = item.getComment() or u''
        new = _append_tag(old, u'group="%s"' % tag)
        if new != old:
            item.setComment(new)
            changed += 1
    return changed


def remove_group(callbacks, start_packet_no, end_packet_no, group_name):
    name = (group_name or u'').strip()
    marker = u'[group="%s"]' % name
    if not name:
        raise ValueError('Group name is empty.')
    changed = packet_no = 0
    for item in callbacks.getProxyHistory():
        packet_no += 1
        if start_packet_no is not None and packet_no < start_packet_no:
            continue
        if end_packet_no is not None and packet_no > end_packet_no:
            break
        old = item.getComment() or u''
        new = old.replace(marker, u'').strip()
        if new != old:
            item.setComment(new)
            changed += 1
    return changed


def clear_bracket_tags(callbacks, start_packet_no=None, end_packet_no=None):
    changed = packet_no = 0
    for item in callbacks.getProxyHistory():
        packet_no += 1
        if start_packet_no is not None and packet_no < start_packet_no:
            continue
        if end_packet_no is not None and packet_no > end_packet_no:
            break
        old = item.getComment() or u''
        new = re.sub(r'\[[^\]\r\n]*\]\s*', u'', old).strip()
        if new != old:
            item.setComment(new)
            changed += 1
    return changed
